DUT:
    Module: alu_pipeline
    Dependencies:
        Packages: 
            core_types_pkg.vh: core_types_pkg
        Includes:
    Parameters: 
    Ports:
        Clock: CLK
        Active_Low_Reset: nRST
        In: 
          # IQ Side
          valid_in: ''
          op_in: '[3:0]'
          is_imm_in: ''
          imm_in: '[31:0]'
          A_unneeded_in: ''
          A_forward_in: ''
          A_bank_in: '[LOG_PRF_BANK_COUNT-1:0]'
          B_forward_in: ''
          B_bank_in: '[LOG_PRF_BANK_COUNT-1:0]'
          dest_PR_in: '[LOG_PR_COUNT-1:0]'
          # PRF Side
          A_reg_read_valid_in: ''
          B_reg_read_valid_in: ''
          ROB_index_in: '[LOG_ROB_ENTRIES-1:0]'
          reg_read_data_by_bank_in: '[PRF_BANK_COUNT-1:0][31:0]'
          forward_data_by_bank_in: '[PRF_BANK_COUNT-1:0][31:0]'
        Out:
          # IQ Side
          ready_out: ''
          # PRF Side
          WB_valid_out: ''
          WB_data_out: '[31:0]'
          WB_PR_out: '[LOG_PR_COUNT-1:0]'
          WB_ROB_index_out: '[LOG_ROB_ENTRIES-1:0]'

Testbench:
    Modport:

Output_Path: ../../uvm/alu_pipeline/MyUVMF_output


        
